# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 897159daac3fa194a11ee32b1c658440b6cb9e5f6697ba012802c5f7c2b19f3287597bbcba7be452c1a1b280c088c99044bd89f03fe9af3a6b64828a6979cbb3

test:
  secret_key_base: d14f063bb84b5945f4d141597abf4cc7fbed9540b8785945d20ba979a785992246a6fe38bfe591f5a31e5678c61641c6c3883003510b5b6746fd17921e321995

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
